/**
 * Skill Auto-Updater
 *
 * Reads skill-improvements.json generated by research-memory hook
 * and automatically updates SKILL.md files when patterns reach
 * high confidence (5+ occurrences across multiple research sessions).
 *
 * This implements the EvoSkill concept: skills that evolve from usage.
 *
 * How it works:
 * 1. After each research session, research-memory hook detects recurring patterns
 * 2. When a pattern appears 5+ times with high confidence, a suggestion is generated
 * 3. This hook reviews suggestions and applies them to SKILL.md files
 * 4. Updated skills make future research more effective
 *
 * Safety: Only appends to SKILL.md, never deletes. Creates backup before each update.
 */

import type { HookFunction } from "../types"

interface SkillImprovement {
  pattern: string
  suggestion: string
  confidence: "low" | "medium" | "high"
  generated_at: string
}

interface SkillImprovementsFile {
  suggestions: SkillImprovement[]
  last_generated: string | null
  applied: SkillImprovement[]
}

export function createSkillAutoUpdaterHook(): HookFunction {
  return async (event, ctx) => {
    if (event.type !== "session.idle") return

    const memoryPath = `${ctx.directory}/.sisyphus/research-memory`
    const improvementsPath = `${memoryPath}/skill-improvements.json`

    try {
      const { readFile, writeFile, mkdir } = await import("fs/promises")
      const { existsSync } = await import("fs")
      const { join } = await import("path")

      if (!existsSync(improvementsPath)) return

      const content = await readFile(improvementsPath, "utf-8")
      const data: SkillImprovementsFile = JSON.parse(content)

      if (!data.suggestions || data.suggestions.length === 0) return

      // Filter high-confidence suggestions that haven't been applied
      const highConfidenceSuggestions = data.suggestions.filter(
        (s) =>
          s.confidence === "high" &&
          !data.applied?.some((a) => a.pattern === s.pattern)
      )

      if (highConfidenceSuggestions.length === 0) return

      const skillsPath = join(ctx.directory, ".opencode", "skills")

      for (const suggestion of highConfidenceSuggestions) {
        // Determine which skill to update based on pattern
        const targetSkill = determineTargetSkill(suggestion.pattern)
        if (!targetSkill) continue

        const skillFilePath = join(skillsPath, targetSkill, "SKILL.md")

        if (!existsSync(skillFilePath)) continue

        // Create backup
        const backupPath = `${skillFilePath}.backup.${Date.now()}`
        await writeFile(backupPath, await readFile(skillFilePath, "utf-8"))

        // Read current skill
        const currentContent = await readFile(skillFilePath, "utf-8")

        // Check if this pattern is already mentioned
        if (currentContent.includes(suggestion.pattern)) continue

        // Append the learned pattern
        const appendix = `\n\n## Learned Pattern: ${suggestion.pattern}\n\n**Detected**: ${suggestion.suggestion}\n**Confidence**: ${suggestion.confidence}\n**First detected**: ${suggestion.generated_at}\n\n> This pattern was auto-detected from ${data.suggestions.filter((s) => s.pattern === suggestion.pattern).length} research sessions.`

        const updatedContent = currentContent + appendix
        await writeFile(skillFilePath, updatedContent)

        // Mark as applied
        if (!data.applied) data.applied = []
        data.applied.push(suggestion)
      }

      // Save updated improvements file
      await writeFile(improvementsPath, JSON.stringify(data, null, 2))

      ctx.log?.info(
        `Skill auto-updater: Applied ${highConfidenceSuggestions.length} improvements to skills`
      )
    } catch (error) {
      ctx.log?.warn(`Skill auto-updater failed: ${error}`)
    }
  }
}

/**
 * Maps detected patterns to the most relevant skill for improvement.
 */
function determineTargetSkill(pattern: string): string | null {
  const patternToSkill: Record<string, string> = {
    abandon: "journey-mapper",
    frustrat: "sentiment-analyzer",
    confus: "ux-heuristics",
    slow: "ux-heuristics",
    expensive: "sentiment-analyzer",
    hidden: "ux-heuristics",
    unclear: "ux-heuristics",
    broken: "ux-heuristics",
    missing: "ux-heuristics",
    difficult: "ux-heuristics",
    complain: "social-listener",
    praise: "social-listener",
    workaround: "web-scraper",
    compare: "social-listener",
    alternative: "social-listener",
    recommend: "social-listener",
    persona: "persona-builder",
    segment: "persona-builder",
    behavior: "persona-builder",
    journey: "journey-mapper",
    touchpoint: "journey-mapper",
    pain: "journey-mapper",
    emotion: "sentiment-analyzer",
    sentiment: "sentiment-analyzer",
    review: "sentiment-analyzer",
    rating: "sentiment-analyzer",
    heuristic: "ux-heuristics",
    accessibility: "ux-heuristics",
    wcag: "ux-heuristics",
    contrast: "ux-heuristics",
    scrape: "web-scraper",
    extract: "web-scraper",
    forum: "web-scraper",
    reddit: "social-listener",
    twitter: "social-listener",
    social: "social-listener",
    methodology: "research-methodology",
    discovery: "research-methodology",
    sample: "research-methodology",
    recruit: "research-methodology",
  }

  for (const [key, skill] of Object.entries(patternToSkill)) {
    if (pattern.toLowerCase().includes(key.toLowerCase())) {
      return skill
    }
  }

  return null
}
