/**
 * Research Planner Plan Template
 *
 * The markdown template structure for research plans generated by Research Planner.
 * Includes TL;DR, context, objectives, methodology, TODOs, and deliverables.
 */

export const PROMETHEUS_PLAN_TEMPLATE = `## Plan Structure

Generate plan to: \`.sisyphus/plans/{name}.md\`

\`\`\`markdown
# {Research Plan Title}

## TL;DR

> **Quick Summary**: [1-2 sentences capturing the core research objective and approach]
> 
> **Deliverables**: [Bullet list of concrete outputs]
> - [Output 1: e.g., Executive Summary Report]
> - [Output 2: e.g., User Personas (3-4)]
> - [Output 3: e.g., Customer Journey Map]
> 
> **Estimated Effort**: [Quick | Short | Medium | Large | XL]
> **Parallel Execution**: [YES - N waves | NO - sequential]
> **Critical Path**: [Task X → Task Y → Task Z]

---

## Context

### Original Request
[User's initial description]

### Interview Summary
**Key Discussions**:
- [Point 1]: [User's decision/preference]
- [Point 2]: [Agreed approach]

**Contextual Research Findings**:
- [Finding 1]: [Implication for research plan]
- [Finding 2]: [Recommendation]

### Consultant Review
**Identified Gaps** (addressed):
- [Gap 1]: [How resolved]
- [Gap 2]: [How resolved]

---

## Research Objectives

### Core Objective
[1-2 sentences: what we're trying to learn and why]

### Research Questions
- [Primary question the research must answer]
- [Secondary questions]

### Target Audience
- [Who we're researching: behaviors, context, not just demographics]

### Product/Service Context
- [What product/service is being researched]
- [Current stage: discovery, evaluation, optimization]

### Definition of Done
- [ ] [Verifiable condition: e.g., "Top 3 pain points identified with direct user quotes"]

### Must Have
- [Non-negotiable research requirement]
- [e.g., "Every finding backed by direct quotes from at least 2 source types"]

### Must NOT Have (Guardrails)
- [Explicit exclusion from Consultant review]
- [Research bias to avoid]
- [Scope boundary]

---

## Methodology

### Research Approach
- **Type**: [Discovery | Evaluative | Diagnosis | Competitive | Mixed]
- **Source Types**: [Social media, forums, reviews, academic, industry reports]
- **Triangulation**: [How findings will be cross-validated]

### Evidence Policy
Every finding MUST include:
- Direct quote or specific data point
- Source type and context (where it came from)
- Date/recency note
- For key findings: support from at least 2 independent source types

**FORBIDDEN:**
- Presenting opinions as findings
- Fabricating quotes or data
- Single-source conclusions for key findings
- Confusing FINDING (what the data shows) with INSIGHT (why it matters)

---

## Execution Strategy

### Parallel Research Waves

> Maximize throughput by grouping independent research tasks into parallel waves.
> Each wave completes before the next begins.
> Target: 5-8 tasks per wave. Fewer than 3 per wave (except final) = under-splitting.

\`\`\`
Wave 1 (Start Immediately — Broad Discovery):
├── Task 1: Social media sentiment scan [quick-lookup]
├── Task 2: Forum complaint analysis [quick-lookup]
├── Task 3: Review site aggregation [quick-lookup]
├── Task 4: Industry benchmark research [quick-lookup]
├── Task 5: Competitor mention tracking [quick-lookup]
└── Task 6: Academic/expert research [quick-lookup]

Wave 2 (After Wave 1 — Deep Dive):
├── Task 7: Thematic analysis of Wave 1 data [thematic-analysis]
├── Task 8: Deep forum investigation on top themes [deep-research]
├── Task 9: User behavior pattern analysis [content-coding]
├── Task 10: Competitive feature comparison [deep-research]
└── Task 11: Visual audit of competitor interfaces [visual-audit]

Wave 3 (After Wave 2 — Synthesis):
├── Task 12: Insight generation and triangulation [thematic-analysis]
├── Task 13: Persona creation from patterns [creative-insights]
├── Task 14: Journey map construction [creative-insights]
└── Task 15: Prioritized recommendations [report-writing]

Wave FINAL (After ALL tasks — Quality Review):
├── Task F1: Evidence verification (Quality Reviewer)
├── Task F2: Triangulation check (Quality Reviewer)
├── Task F3: Actionability review (Quality Reviewer)
└── Task F4: Bias and gap analysis (Quality Reviewer)
-> Present results -> Get explicit user okay

Critical Path: Task 1 → Task 7 → Task 12 → Task 13 → F1-F4 → user okay
Parallel Speedup: ~60% faster than sequential
Max Concurrent: 6 (Waves 1 & 2)
\`\`\`

---

## TODOs

> Research + Synthesis = ONE Task. Never separate.
> EVERY task MUST have: Recommended Category + Skills + Evidence Requirements.
> **A task WITHOUT evidence requirements is INCOMPLETE. No exceptions.**

- [ ] 1. [Task Title]

  **What to do**:
  - [Clear research steps]
  - [What to look for]
  - [What sources to consult]

  **Must NOT do**:
  - [Specific exclusions]
  - [Biases to avoid]

  **Recommended Research Profile**:
  > Select category + skills based on task domain. Justify each choice.
  - **Category**: \`[visual-audit | thematic-analysis | deep-research | creative-insights | quick-lookup | content-coding | report-writing | comprehensive-study]\`
    - Reason: [Why this category fits the task domain]
  - **Skills**: [\`skill-1\`, \`skill-2\`]
    - \`skill-1\`: [Why needed - domain overlap explanation]
  - **Skills Evaluated but Omitted**:
    - \`omitted-skill\`: [Why domain doesn't overlap]

  **Parallelization**:
  - **Can Run In Parallel**: YES | NO
  - **Parallel Group**: Wave N (with Tasks X, Y) | Sequential
  - **Blocks**: [Tasks that depend on this task completing]
  - **Blocked By**: [Tasks this depends on] | None (can start immediately)

  **Evidence Requirements** (CRITICAL):

  > The executor has NO context from your interview. Evidence requirements are their ONLY guide.
  > Each requirement must answer: "What evidence do I need and WHY?"

  **Source Types to Consult**:
  - [e.g., Reddit threads about checkout frustration]
  - [e.g., Twitter mentions of the product]
  - [e.g., App store reviews]

  **Evidence Format**:
  - Direct quotes (minimum 5 per theme)
  - Specific data points with source
  - Screenshots or visual evidence where relevant

  **WHY Each Source Matters** (explain the relevance):
  - Don't just list sources - explain what insight each source type provides
  - Bad: "Check Reddit" (vague, which subreddits? what to look for?)
  - Good: "r/ecommerce and r/smallbusiness — look for checkout complaints, specifically about hidden fees and form complexity"

  **Acceptance Criteria**:

  > **EVIDENCE-BASED VERIFICATION ONLY** — No opinions or interpretations without data.
  > Every criterion MUST be verifiable by checking for specific evidence.

  - [ ] Minimum N direct quotes collected from source type X
  - [ ] At least 2 independent source types consulted
  - [ ] Key findings triangulated across sources

  **Triangulation Requirements** (for key findings):
  - Finding must be supported by at least 2 source types
  - Note any contradictory evidence and how it was resolved
  - Distinguish between universal patterns and edge cases

  **Deliverable**: [What this task produces: e.g., "List of top 5 checkout complaints with quotes"]

---

## Synthesis Strategy

> After all research tasks complete, synthesize findings into coherent insights.

### Synthesis Steps
1. **Content Coding**: Tag and categorize all findings
2. **Thematic Analysis**: Group codes into organizing themes
3. **Insight Generation**: Identify the "why" behind patterns
4. **Triangulation**: Cross-validate across source types
5. **Recommendation**: Translate insights into actionable steps

### Quality Gates
- Every insight backed by specific evidence
- Key findings triangulated (2+ source types)
- Recommendations specific and prioritized
- Bias check: actively sought disconfirming evidence

---

## Deliverable Plan

### Primary Deliverables
- [ ] **Executive Summary** (1 page): Top 3 findings + Top 3 recommendations
- [ ] **Detailed Findings Report**: Structured by theme with evidence
- [ ] **Prioritized Recommendations**: Effort vs Impact matrix

### Secondary Deliverables (if applicable)
- [ ] **User Personas** (3-4): Based on behavioral patterns
- [ ] **Customer Journey Map**: Current state with pain points
- [ ] **Competitive Analysis**: Feature and positioning comparison

---
`
