import { z } from "zod"

export const HookNameSchema = z.enum([
  "todo-continuation-enforcer",
  "context-window-monitor",
  "session-recovery",
  "session-notification",
  "tool-output-truncator",
  "directory-agents-injector",
  "directory-readme-injector",
  "empty-task-response-detector",
  "think-mode",
  "model-fallback",
  "preemptive-compaction",
  "background-notification",
  "auto-update-checker",
  "keyword-detector",
  "agent-usage-reminder",
  "non-interactive-env",
  "interactive-bash-session",
  "thinking-block-validator",
  "category-skill-reminder",
  "compaction-context-injector",
  "compaction-todo-preserver",
  "auto-slash-command",
  "prometheus-md-only",
  "sisyphus-junior-notepad",
  "unstable-agent-babysitter",
  "task-resume-info",
  "tasks-todowrite-disabler",
  "runtime-fallback",
  "write-existing-file-guard",
  "rules-injector",
  "research-memory",
  "anthropic-effort",
  "legacy-plugin-toast",
  "no-hephaestus-non-gpt",
  "question-label-truncator",
  "start-work",
  "no-sisyphus-gpt",
  "edit-error-recovery",
  "delegate-task-retry",
  "anthropic-context-window-limit-recovery",
  "startup-toast",
  "ralph-loop",
  "atlas",
  "skill-auto-updater",
  "stop-continuation-guard",
])

export type HookName = z.infer<typeof HookNameSchema>
